### ISSUE TITLE
Getting 500 error

### ISSUE THREAD

**Issue by cesarhenrq** [kitloong/json-server-vercel#1]
When i try to post some in my db.json, i'm getting a 500 error on http request. The post is did but the response in code get a error and the code stops working. If you test the endpoint in postman, you will receive the following warning: 

Error: EROFS: read-only file system, open 'db.json'
    at Object.openSync (node:fs:600:3)
    at writeFileSync (node:fs:2221:35)
    at FileSync.write (/var/task/node_modules/.pnpm/lowdb@1.0.0/node_modules/lowdb/adapters/FileSync.js:53:14)
    at db.write (/var/task/node_modules/.pnpm/lowdb@1.0.0/node_modules/lowdb/lib/main.js:37:21)
    at /var/task/node_modules/.pnpm/json-server@0.17.0/node_modules/json-server/lib/server/router/write.js:5:8
    at Layer.handle [as handle_request] (/var/task/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/task/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/route.js:144:13)
    at create (/var/task/node_modules/.pnpm/json-server@0.17.0/node_modules/json-server/lib/server/router/plural.js:246:5)
    at Layer.handle [as handle_request] (/var/task/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/task/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/route.js:144:13)

Can you help me, please?

**Comment by cesarhenrq** [comment]
Brah, i was on web and i found this function "const fs = require('fs');
fs.chmodSync('db.json')". I don't even know how to use programm with node.js and him packages or even how to add the permisions to the code. But i think that it will fix this inssue.

**Comment by kitloong** [comment]
Hi @cesarhenrq , thanks for using this template. 

I think the error message explains itself, you are trying to write a read only file. 
You may need to chmod your file with write permission.

Anyway, I will close the issue now since it is not related to the template.

**Comment by cesarhenrq** [comment]
Can you explain me how i do that?

**Comment by cesarhenrq** [comment]
> Hi @cesarhenrq , thanks for using this template.
> 
> I think the error message explains itself, you are trying to write a read only file. You may need to chmod your file with write permission.
> 
> Anyway, I will close the issue now since it is not related to the template.

Hi @kitloong, thank you for your reply!

**Comment by Mbitoz** [comment]
Hi @cesarhenrq , did you solve the error ?

**Comment by cesarhenrq** [comment]
No, bro. I'm not a node developer.
